apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tob7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-tob7@sha256:f1ad136527f295dae326b87e1c1da4ec5625a72cfc9d1406ff136c5f932022aa
        name: my-nodejs
        resources: {}
status: {}
